# Generated by Django 6.1 on 2026-08-25 05:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIPVisitor',
            fields=[
                ('pass_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected'), ('ENTERED', 'Entered'), ('EXITED', 'Exited')], default='EXPECTED', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntryExitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.vipvisitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
